# Schema for the configuration files of the Analyze module.
analyze.settings:
  type: config_object
  label: 'Analyze settings'
  mapping:
    status:
      type: mapping
      label: 'Plugin Status'
