analyze_hello_world.settings:
  type: config_object
  label: 'Sentiment Analysis Settings'
  mapping:
    sentiments:
      type: sequence
      label: 'Sentiments'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
            label: 'ID'
          label:
            type: label
            label: 'Label'
          min_label:
            type: label
            label: 'Minimum Label'
          mid_label:
            type: label
            label: 'Middle Label'
          max_label:
            type: label
            label: 'Maximum Label'
          weight:
            type: integer
            label: 'Weight' 